### ISSUE TITLE
JDBCToGCS Template timestamp datatype are wrongly converted to integer in avro files

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#102]
JDBCToGCS Template (can be true for other templates too)
Timestamp datatype are wrongly converted to integer in avro files

Replication steps:

1. Create sample data in MySQL with timestamp values.
2. Run template to export data.
3. Use BigQuery to read the generated avro files.

**Comment by vanshaj-google** [comment]
@shashank-google tried to recreate the scenario. I can verify the Avro files created by the templates is having appropriate datatypes as per the create table DDL:
<img width="736" alt="Screenshot 2022-05-30 at 3 37 49 PM" src="https://user-images.githubusercontent.com/105878445/171032747-ade51be7-95ef-4ded-8ff7-f16cea1ce70e.png">

Create Table DDL:
```
CREATE TABLE employee
(
   EmpCode      INT(4),
   EmpFName     VARCHAR(15),
   EmpLName     VARCHAR(15),
   Job          VARCHAR(45),
   SCE      CHAR(4),
   HireDate     DATE,
   Salary       INT(6),
   Commission   BIGINT(8),
   DEPTCODE     BIGINT(8),
   t1 TIMESTAMP
);
```
Working on the # 3 reading generated Avro files at BQ. Will update the thread soon.

**Comment by vanshaj-google** [comment]
@shashank-google Trying to replicate the issue, the behaviour of converting the timestamp & date type fields to INTEGER while impoorting directly to BQ is expected. This is because BQ does not support the AVRO logical data types by default, until specified explicitly.
ref.[ https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro#logical_types]( https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro#logical_types)

As mentioned unless we explicitly set the value of use_avro_logical_types or useAvroLogicalTypes (while using bq command line tool), the conversion from Avro logical types to their corresponding BigQuery data types won't happen.

Alternatively, you can also create an external table by setting above property as follows:
```
CREATE EXTERNAL TABLE test.test_avro_ext_logical_types
OPTIONS (
  format = 'AVRO',
  uris = ['gs://test/out_jdbc/*.avro']
  enable_logical_types = TRUE
)
```

**Comment by vanshaj-google** [comment]
This does not hold true for other templates loading data to BQ from Avro files.
The explicit conversion of Avro logical types to BigQuery data types is not required as BQ takes schema details from the Spark DataFrame directly without referring the underlying Avro files metadata.

_Batch ID: 6f925bcc5d0f48fca5d335279ad21595_ (testing Avro to BQ, having date and timestamp fields)

**Comment by shashank-google** [comment]
Interesting!
Context: I spotted this issue in exporting data from MySql table into avro and then importing into Cloud Spanner.

So what you seem to be saying that there is no issue in generating the avro files. But mainly when importing / loading data in target system like Spanner. Also please test the same for GCSToJDBC template as well.

Can you please figure out solution so that Spanner or JDBC schema is generated with Timestamp column instead of Integer.

**Comment by vanshaj-google** [comment]
@shashank-google The type conversion from date/ timestamp to integer is bound to happen with BigQuery only, if we do not specify explicitly to use logical types.
This would not be the case for GCStoJDBC or GCStoSpanner templates. To verify the same I ran the respective templates and found the data & timestamp fields inserting correctly and retaining their datatypes.

Batch ID: 1f779a4bd80a474e93edfe87792b206c [GCStoSpanner]
Batch ID: 9540c182720245a584c5cc2d04704e6c [GCStoSpanner]

Output Table: avrodemo
