### ISSUE TITLE
[documentation] Update readme links as deep links

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#328]
Update /README.md /java/README.md /python/README.md link to deep link of that particular template heading.

**Comment by hhasija** [comment]
> Unfortunately it is not working. Though changes look right, but github is not auto scrolling. It feels like it is not feasible.

So @shashank-google , it is working fine when we are providing an absolute URL instead of a relative URL. For Example, 

* [HiveToBigQuery](https://github.com/GoogleCloudPlatform/dataproc-templates/tree/main/java/src/main/java/com/google/cloud/dataproc/templates/hive#1-hive-to-bigquery)

The only issue is that, it would always point to the main branch read me file. Do you think so, we should go ahead with this ?

**Comment by hhasija** [comment]
@shashank-google Any suggestions on above mentioned approach ?
