### ISSUE TITLE
[spike] [python / java] Log and Ignore bad records during spark writes 

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#392]
Example scenario:
While running say GCSToJDBC (or JDBCToJDBC) template you are writing into a table in mysql with 'int' column type.
But one of the row has instead value larger than int's size.

Goal 1:
As a result template should not fail, instead log the error row and continue with remaining records.

Goal 2:
Log the errors only until a default say MAX_IGNORE_ERRORS = 5
So it should log the errors for first 5 occurrences and job should fail only on 6th time.

**Comment by PoulamiR1994** [comment]
This approach can be considered based on testing with CSV files :
1. We first read the output table and get its schema alone, without loading all the existing data of the table
2. While reading the input, we then use this schema using PERMISSIVE mode as an option. This option checks for errors in the input and inserts concatenated values of the invalid rows to an additional column called "_corrupted_record".
3. The "_corrupted_record" column can then be used to filter out the invalid rows, which can then be logged or used to raise an exception based on their count and the threshold value set for number of errors .

Known Issues in the Approach:
Since Spark 2.3, the queries from raw JSON/CSV files are disallowed when the referenced columns only include the internal corrupt record column (named _corrupt_record by default). For example: spark.read.schema(schema).json(file).filter($"_corrupt_record".isNotNull).count() and spark.read.schema(schema).json(file).select("_corrupt_record").show(). Instead, you can cache or save the parsed results and then 
send the same query. For example, val df = spark.read.schema(schema).json(file).cache() and then df.filter($"_corrupt_record".isNotNull).count().;

As a workaround, we can filter out the error rows based on the values of  "_corrupted_record" column, cache this dataframe and then proceed. Only issue is this might lead to memory issues if there are a lot of errors.

**Comment by PoulamiR1994** [comment]
Tested the above approach with the remaining data types i.e. JSON, Parquet and Avro and following are the results :

1.  JSON : The approach detailed above for CSV works similarly for JSON and we are able to take care of both the goals mentioned in the Spike.
2. Parquet : Parquet being columnar, has a different method of determining the schema of the underlying files. Hence, the approach mentioned above doesn't work. In order to prevent the template from failing, we can set the configuration (spark.sql.files.ignoreCorruptFiles=true") , which will ignore all the corrupt files i.e. parquet files whose schema doesn't match with our provided schema (loaded from output JDBC table). The only caveat with this approach is that we don't have the granularity of row-level errors as we get for CSV and JSON. We may consider logging the names of the ignored files for the benefit of the user, but that will lead to excessive memory usage.
3. AVRO : Testing is in progress for AVRO data format.

**Comment by PoulamiR1994** [comment]
The above solution is being reviewed, waiting for confirmation to proceed.
