### ISSUE TITLE
Upgrade dataproc serverless version to 1.2 Java

### ISSUE THREAD

**Issue by shashank-google** [GoogleCloudPlatform/dataproc-templates#938]
https://cloud.google.com/dataproc-serverless/docs/concepts/versions/dataproc-serverless-versions#supported-dataproc-serverless-for-spark-runtime-versions

Upgrade Dataproc Serverless runtime version from 1.1 to 1.2
Needs to be done for both Java and Python.

**Comment by rajc242** [comment]
Team if you check the difference between 1.2 and 2.2 runtime then it's only Scala version difference otherwise rest all are the same between both versions. [Document](https://cloud.google.com/dataproc-serverless/docs/concepts/versions/spark-runtime-versions#spark_runtime_version_12)

I wonder if we can dynamically allow customers to choose between both of them if possible.

**Comment by rajc242** [comment]
I created a branch `938-upgrade-dataproc-serverless-version-to-12`. Started development work for java.
